### ISSUE TITLE
Add `Duration::as_millis()`?

### ISSUE THREAD

**Issue by zhongzc** [jedisct1/rust-coarsetime#11]
It seems to lack this commonly used function.  By calling both `Duration::as_secs()` and `Duration::subsec_nanos()` can construct a `millis` but, IMO, it not good as just `Duration::as_millis()`.

**Comment by jedisct1** [comment]
Can you send a pull request for this?

**Comment by zhongzc** [comment]
> Can you send a pull request for this?

I 'm not sure it's the right way: reverse `helper::_millis_to_u64()` to `(dur.0 << 8) / 1_099_511_628`

**Comment by jedisct1** [comment]
Divisions are very slow, but shifts and multiplications are fast. So the goal is to replace divisions with mul+shift.

The base is `2^32`, so for nanoseconds, we multiply by `125000000` since we have `125_000_000*(2^32) / (2^29) = 1000000000`. There is no precision loss with a 29 bit shift.

For milliseconds that would just be `((self.0 as u32 as u64 * 125) >> 29) as u32`.
