### ISSUE TITLE
Old MacOS support

### ISSUE THREAD

**Issue by Plecra** [jedisct1/rust-coarsetime#13]
Without 49db05c3c5d38f919e82b92842859c63e67352ff, the library cannot be compiled for older macOS versions without the `clock_gettime_nsec_np` API. This forces Anki to use a [fork that reverts the change](https://github.com/ankitects/rust-coarsetime/commit/f9e2c86216f0f4803bc75404828318fc206dab29).

Could this change be upstreamed?

**Comment by jedisct1** [comment]
El Capitan has reached end of life.

It is not supported any longer by Apple since October 31, 2019.

I don't have any devices running it and this version is not available on CI platforms any more.

So it is probably not worth keeping untestable code for an operating system that even that has been phased out.

**Comment by Plecra** [comment]
There wouldn't be any code that targeted El Capitan, it'd be fine to just use the fallback `unix` implementation like before, and there wouldn't been any untestable code introduced. This would just make the specialized Sierra+ code optional for the user.

I'm not particularly aware of the state of MacOS, but El Capitan seems comparable to Windows 7 to me: Vendor support was phased out recently, but [a number of systems still run on it](https://gs.statcounter.com/macos-version-market-share/desktop/worldwide) due to reasons they can't be updated. It may not be worth a significant investment, but giving users the option can be helpful.
